# Generated by Django 5.2 on 2025-09-12 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_content_options_alter_module_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Content',
        ),
    ]
